name: Build APK from ZIP (auto-fix)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Unzip Android project
        id: unzip
        run: |
          unzip -q StockSyncApp_v3.zip -d project
          echo "📂 Folder hasil ekstrak:"
          ls project
          found=$(find project -name "gradlew" | head -n 1)
          echo "gradle_path=$found" >> $GITHUB_ENV
          echo "Found gradlew at: $found"

      - name: Build debug APK
        run: |
          cd $(dirname $gradle_path)
          chmod +x ./gradlew || true
          ./gradlew assembleDebug

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: project/**/app/build/outputs/apk/debug/*.apk
